services:
  - type: web
    name: documind-ai
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip uninstall pinecone-client pinecone -y || true
      pip cache purge
      pip install -r requirements.txt
    startCommand: python minimal_main.py
    healthCheckPath: /health
    envVars:
      - key: VECTOR_DB_PROVIDER
        value: pinecone
      - key: RERANKER_PROVIDER
        value: cohere
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: 3.11.0
